### ISSUE TITLE
Max upload size issue

### ISSUE THREAD

**Issue by jondron** [ColdTrick/advanced_notifications#1]
Enabling advanced_notifications causes any save of any object (blog, wire post, whatever) to make Elgg report a max post size exceeded error. The system message is:
* The size of file(s) uploaded exceeded the limit set by your site administrator. 

The max posts on the server is set at 32M and max upload set at 24M.
The problem goes away when the plugin is disabled. 
This is the same problem as that noted by UK at http://community.elgg.org/discussion/view/1524467/i-have-a-weird-error

Jon

**Comment by jeabakker** [comment]
sorry we didn't get back to this issue.

We're currently rewriting the plugin for Elgg 2.0+ and this means we basically start from scratch as Elgg 2.0 does everything this plugin offered.

So closing this issue
