### ISSUE TITLE
Issue with session_id

### ISSUE THREAD

**Issue by juliendangers** [ColdTrick/advanced_notifications#3]
Hello,

Have you ever had any issue with session when using cli ? We are using it on a closed community and we are facing the following issue

When we create/update a new group discussion, session_id is passed to cli, but once __elgg_session_boot is called (`/engin/lib/sessions.php`) $_SESSION object only has `__elgg_session`. So call to `elgg_get_annotation_from_id` is done while get_loggedin_user returns 0, and access_id checks are performed on invalid values. Here is the SQL query (access_id should have many other values, and the required one is 54)

```
SELECT DISTINCT n_table.*, n.string as name, v.string as value FROM elggannotations n_table JOIN elggentities e ON n_table.entity_guid = e.guid  JOIN elggmetastrings n on n_table.name_id = n.id  JOIN elggmetastrings v on n_table.value_id = v.id  WHERE  (n_table.id IN (3191) AND (  (n_table.access_id IN (2,-5)
			OR (n_table.owner_guid = -1)
			OR (
				n_table.access_id = 0
				AND n_table.owner_guid = -1
			)
		) and n_table.enabled='yes')) AND (  (e.access_id IN (2,-5)
			OR (e.owner_guid = -1)
			OR (
				e.access_id = 0
				AND e.owner_guid = -1
			)
		) and e.enabled='yes')
```

**Comment by jeabakker** [comment]
sorry we didn't get back to this issue.

We're currently rewriting the plugin for Elgg 2.0+ and this means we basically start from scratch as Elgg 2.0 does everything this plugin offered.

So closing this issue
